### ISSUE TITLE
RequiredWith and extra validation not working as expected

### ISSUE THREAD

**Issue by pachico** [siriusphp/validation#43]
Hello, I'm creating a middleware that implements your validation. Unfortunately, I'm having issues with a mixed validation.
Hopefully, you can help me out.
My rules are:
```php
$validator = new \Sirius\Validation\Validator();
$validator->add(
    [
        'latitude' => ['requiredWith(longitude)', 'number'],
        'longitude' => ['requiredWith(latitude)', 'number']
    ]
);

$result = $validator->validate([]);
var_dump($result); // Returns false

```
In theory, the `number` rule should be checked for both latitude and longitude, if any of the two is passed, but it reality it does not and validate returns false.

Am I setting the rules incorrectly or is this the expected behaviour?

I'm running version 2.2, PHP 7.1

**Comment by adrianmiu** [comment]
Hi. 

Unfortunately this is a bug. I will try to fix it asap but I'm a bit swamped at the moment.
If you have PR i'd be happy to accept it :)

**Comment by pachico** [comment]
Not sure when I'll have time to look at it during the next 2 weeks. :(

**Comment by eclipxe13** [comment]
As far I can see the problem is not inside rules. The problem is inside `ValueValidator::validate`:

The current logic is:
a. determine if the rules set contains a `Required` rule (`$isRequired`).
b. if is not required `! $isRequired` and value is not set then exit and don't evaluate anything.
c. evaluate each rule
    a. perform rule validation
    b. exit the loop if `$isRequired` and the rule fail
d. return if there were errors

The problem is that in step "c" it is expected that all the rules validate positive. So, for the set of requiredWith & number, the first evaluate to true but the second evaluates to false.

I think I solve this issue by making a two step evaluation:
1. Evaluate each rule that is an instance of `Required`.
2. Exit if is not required `! $isRequired` and value is not set.
3. Evaluate each rule that is a not an instance of `Required`.
4. Return if there were errors.

I'm preparing a PR for this... stay tuned.

**Comment by eclipxe13** [comment]
Final steps of fix are:

1. Evaluate each rule that is an instance of `Required`, return `false` on failure.
2. Exit if value is not set (required rules has been evaluated previously).
3. Evaluate each rule that is a not an instance of `Required`.
4. Return if there were errors.

PR #44 was created

**Comment by adrianmiu** [comment]
@eclipxe13 Thank you for the PR!
