### ISSUE TITLE
Contribution guide?

### ISSUE THREAD

**Issue by eclipxe13** [siriusphp/validation#45]
Hi, I would like to participate in your project, do you have a contribution guide? to-do list? or some info I could use to help?

I think you maintain compatibility with PHP 5.3 because of WP. Is my assumption right?

Have you consider open a communication line like gitter?

These are some ideas:
- setup phpunit testing (like phpunit.dist.xml in the root)
- setup project files more standard (follow pds/skeleton?)
- fix phpcpd issues
- improve travis-ci (set sudo false, post code coverage only on one php run)

**Comment by adrianmiu** [comment]
@eclipxe13 
Thank you for your involvement.

I was thinking about writting a version 3 that will break the compatibility with version 2 but I am swamped at the moment. To anwser your questions:

1. The project started without support for 5.3. The library is used by `sirius/upload` which is used by Bolt CMS, which supported 5.3. Because the library didn't have support for 5.3 somebody took the code and created a different 5.3 version by only changing 2 lines of code. That was without submitting a PR. Anyway, I made the change in my library and the guy agreed to use mine instead
2. I don't know what is (or should be) the difference between `phpunit.xml` and `phpunit.dist.xml`
3. Yes, using pds/skeleton was on the list for version 3
4. PHPCPD is on the list too
5. I am open to the travis-ci changes if you explain the benefits

**Comment by pachico** [comment]
Good morning, guys.
I see this library as a perfect tool to create PSR7 middleware validation layers, particularly for rest(ful|ish) apps.
The reason why I stopped using it was the bug that you @eclipxe13  seem to have solved.
If I may contribute to the answers:
1. If you are going to do a new version, please bump minimum requirement to at least php 7.0 (latest versions of frameworks are going to do that too)
2.phpunit, if no config is manually loaded, will try to load a config with names phpunit.xml or phpunit.dist.xml. Both do the same thing.
3. I would rather use https://github.com/thephpleague/skeleton as skeleton, instead.

Cheers

**Comment by adrianmiu** [comment]
@pachico 

1. I don't see a reason to remove support for 5.6 for the next version... unless I will start working on it to far in the future.
2. I like thephpleague skeleton better

**Comment by pachico** [comment]
You're right, if 5.6 is still getting fixes, it's a valid version to code against.

**Comment by eclipxe13** [comment]
I think article contribute to the argument to support PHP 5.6: https://www.brandonsavage.net/version-php-package-support/

Anyhow. the package has not been maintained for a while, is it going to be any future on this project?

**Comment by adrianmiu** [comment]
@eclipxe13 
I am using the package in all my projects (even Laravel projects) so it's here to stay. However I'm swamped with work and I couldn't find the time to work on it :(
I am open to pull-requests though
