### ISSUE TITLE
Rule GreaterThan(0) is not work

### ISSUE THREAD

**Issue by sergiobelya** [siriusphp/validation#46]
And another rules that may contain value 0 as param are not working (likely).
This is related for rules that declared as a string.
Cause, see
`ValueValidator::parseRule()` - https://github.com/siriusphp/validation/blob/2.2.0/src/ValueValidator.php#L220
and
`AbstractRule::normalizeOptions()` - https://github.com/siriusphp/validation/blob/2.2.0/src/Rule/AbstractRule.php#L93

Row
```php
if (isset($matches[1][0]) && $matches[1][0]) {
```
may be replace to
```php
if (isset($matches[1][0]) && $matches[1][0] !== '') {
```
but
```php
if (! $options) {
```
I don't know how to fix it correctly.

**Comment by eclipxe13** [comment]
You are right, a quick workaround is to set the rule with the non-minimal sintax:
Change `'0'` to `'min=0'`.

This is because `var_dump((bool) '0'); // bool(false)` and the developer use a lot of simple string to boolean comparisons.

**Comment by sergiobelya** [comment]
@eclipxe13 @adrianmiu Thanks for your work.
There are doubts that `ValueValidator::parseRule($ruleAsString)` will not process parameter `"0"`.
But I can check up it not earlier than Monday, January 29th.

**Comment by eclipxe13** [comment]
@sergiobelya You are right. `ValueValidator::parseRule` has the same problem. I don't know why it has to evaluate to truly. anyhow `AbstractRule` already know how to handle with this. I think that you can use the same workaround: change `"0"` to `"min=0"`.

I encourage you to try to fix this, if you want to we can chat about it, if you can't or don't want to tell me to make the tests and a PR with the fix.

**Comment by sergiobelya** [comment]
@eclipxe13 I can assume that it's enough to correct the line https://github.com/siriusphp/validation/blob/2.2.0/src/ValueValidator.php#L220
as indicated in my first comment.
But I can be wrong.
I can try to fix this and add the tests, but with the tests there may be problems. Nevertheless, I will try.

**Comment by eclipxe13** [comment]
Inside the tests folder there is a file called ValueValidarorTest.php Your
test should be in that file. Add a method to the class with your case and
your expected response. See the other methods as example.

Would you like to Google hangout to help you with this?

El 27 ene. 2018 4:26 AM, "Sergei Belyakov" <notifications@github.com>
escribió:

@eclipxe13 <https://github.com/eclipxe13> I can assume that it's enough to
correct the line https://github.com/siriusphp/validation/blob/2.2.0/src/
ValueValidator.php#L220
as indicated in my first comment.
But I can be wrong.
I can try to fix this and add the tests, but with the tests there may be
problems. Nevertheless, I will try.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/siriusphp/validation/issues/46#issuecomment-360975473>,
or mute the thread

**Comment by adrianmiu** [comment]
Fixed. Thank you @sergiobelya

**Comment by sergiobelya** [comment]
And thank you @eclipxe13 @adrianmiu
